### PR TITLE
Add a deploy script to deploy earl from tagged github version.

### PR DESCRIPTION
**Pull request by hzeller**

### CODE REVIEW

**Review by SuperQ — COMMENTED** [review]
It's way easier to do this with ansible :-)

**Comment by hzeller** [comment]
But I don't know ansible (and I prefer a shell-script to a Python script for mission critical things)

**Comment by hzeller** [comment]
(But I am open to pull requests that do this with ansible, if you help install ansible on earl to get it going there.)

**Comment by SuperQ** [comment]
There's nothing to get on the box except ssh keys. Ansible operates remotely via ssh, so there's nothing local necessary except /usr/bin/python.

**Comment by hzeller** [comment]
I want to keep the ssh access to earl as tight as possible to minimize breaches, so this really should be called locally or remotely with my key (but in that case I can do it locally as well).

**Pull request closed without merging**
